ui:
  replicaCount: 1
  image:
    repository: drcoyote/crawler_ui
    tag: latest
  service:
    name: ui
    type: NodePort
    externalPort: 8000
  # Database host configuration
  mongodbHost:
  # Database port configuration
  mongodbPort:

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx

bot:
  replicaCount: 1
  image:
    repository: drcoyote/crawler
    tag: latest
  service:
    name: bot
  # Database host configuration
  mongodbHost:
  # Database port configuration
  mongodbPort:

rabbitmq:
  replicaCount: 1
  image:
    repository: rabbitmq:3.8-rc
  service:
    name: rabbitmq
    type: ClusterIP
    port: 5672
    distPort: 25672
    managerPort: 15672
