apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: crawler
    component: {{ template "rabbitmq.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "{{ .Values.service.port }}"
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}

  - name: "{{ .Values.service.distPort }}"
    port: {{ .Values.service.distPort }}
    protocol: TCP
    targetPort: {{ .Values.service.distPort }}

  - name: "{{ .Values.service.managerPort }}"
    port: {{ .Values.service.managerPort }}
    protocol: TCP
    targetPort: {{ .Values.service.managerPort }}

  selector:
    app: crawler
    component: {{ template "rabbitmq.name" . }}
    release: {{ .Release.Name }}
