{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host | default .Release.Name }}
    secretName: testsecret-tls
  rules:
  - host: {{ .Values.ingress.host | default .Release.Name }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "ui.fullname" . }}
            servicePort: {{ .Values.service.externalPort }}
{{- end -}}
