---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: crawler
    component: {{ template "ui.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      name: {{ .Values.service.name }}
  selector:
    app: crawler
    component: {{ template "ui.name" . }}
    release: {{ .Release.Name }}
