---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: crawler
    component: rabbitmq
spec:
  ports:
    - name: clients
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: mgmt
      port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    app: crawler
    component: rabbitmq
