---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ui
  labels:
    app: crawler
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: ui
  template:
    metadata:
      name: ui
      labels:
        app: crawler
        component: ui
    spec:
      containers:
        - image: 4babushkin/crawler_ui
          name: ui
          env:
            - name: MONGO
              value: mongodb
            - name: MONGO_PORT
              value: "27017"
