---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "bot.fullname" . }}
  labels:
    app: crawler
    component: bot
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: crawler
      component: bot
      release: {{ .Release.Name }}
  template:
    metadata:
      name: bot
      labels:
        app: crawler
        component: bot
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: 4babushkin/crawler_bot
          name: bot
          env:
            - name: MONGO
              value: {{ .Values.mongodbHost | default (printf "%s-mongodb" .Release.Name) }}
            - name: MONGO_PORT
              value: {{ .Values.mongodbPort | default "27017" | quote }}
            - name: RMQ_HOST
              value: {{ .Values.rabbitmqHost | default (printf "%s-rabbitmq" .Release.Name) }}
            - name: RMQ_QUEUE
              value: {{ .Values.rabbitmqQueue | default (printf "%s-crawler" .Release.Name) }}
            - name: RMQ_USERNAME
              value: {{ .Values.rabbitmqUsername | default (printf "%s-rabbitmq" .Release.Name) }}
            - name: RMQ_PASSWORD
              value: {{ .Values.rabbitmqPassword | default (printf "%s-rabbitmq" .Release.Name) }}
            - name: URL
              value: {{ .Values.botUrl | default (printf "%s-https://vitkhab.github.io/search_engine_test_site/" .Release.Name) }}
            - name: EXCLUDE_URLS
              value: {{ .Values.botExcludeUrls | default ".*github.com" | quote }}
